<a href="https://colab.research.google.com/github/imchinmay/Python/blob/main/01_Basics/23_Pandas_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Intro

## Overview

### Notes

* **Pandas** is a Python library used for working with data sets.
* It lets us analyze, clean, explore and manipulate data.
* Pandas primarily uses two data structures to store data:
    * **Series**: A one-dimensional array with data labels, called its index, capable of holding any data type. It's like a column in a spreadsheet.
    * **DataFrame**: A two-dimensional, mutable table with labeled axes (rows and columns). It resembles a spreadsheet or SQL table and can contain multiple Series objects of different data types.

### Importance

* Pandas is one of the most popular and most used library for working with data is Pandas.
* It provides functions for data manipulation, from simple data aggregation to complex merging and joining of datasets.
* Lets us analyze big data and use statistics.
* Works well with other Python libraries, enhancing its functionality for numerical computations and visualizations.

### Import

* First before we even use the library we have to load it in our environment and import it using the `import` command.
* Also once we import it we are going to rename it to `pd`, which is a common alias we give a library. It makes it easier to type out instead of having to type out `pandas` every time. It's technically optional, but it is convention to do this.

NOTE: If running this locally with conda you need to install pandas (ignore if running in Colab).

In [1]:
!pip list

Package                               Version
------------------------------------- ------------------
absl-py                               1.4.0
absolufy-imports                      0.3.1
accelerate                            1.10.1
aiofiles                              24.1.0
aiohappyeyeballs                      2.6.1
aiohttp                               3.12.15
aiosignal                             1.4.0
alabaster                             1.0.0
albucore                              0.0.24
albumentations                        2.0.8
ale-py                                0.11.2
alembic                               1.16.5
altair                                5.5.0
annotated-types                       0.7.0
antlr4-python3-runtime                4.9.3
anyio                                 4.10.0
anywidget                             0.9.18
argon2-cffi                           25.1.0
argon2-cffi-bindings                  25.1.0
array_record                          0.8.1
arrow                                 1.3.0
arviz                                 0.22.0
astropy                               7.1.0
astropy-iers-data                     0.2025.9.1.0.42.11
astunparse                            1.6.3
atpublic                              5.1
attrs                                 25.3.0
audioread                             3.0.1
Authlib                               1.6.3
autograd                              1.8.0
babel                                 2.17.0
backcall                              0.2.0
beartype                              0.21.0
beautifulsoup4                        4.13.5
betterproto                           2.0.0b6
bigframes                             2.18.0
bigquery-magics                       0.10.3
bleach                                6.2.0
blinker                               1.9.0
blis                                  1.3.0
blobfile                              3.0.0
blosc2                                3.7.2
bokeh                                 3.7.3
Bottleneck                            1.4.2
bqplot                                0.12.45
branca                                0.8.1
Brotli                                1.1.0
build                                 1.3.0
CacheControl                          0.14.3
cachetools                            5.5.2
catalogue                             2.0.10
certifi                               2025.8.3
cffi                                  1.17.1
chardet                               5.2.0
charset-normalizer                    3.4.3
chex                                  0.1.90
clarabel                              0.11.1
click                                 8.2.1
cloudpathlib                          0.22.0
cloudpickle                           3.1.1
cmake                                 3.31.6
cmdstanpy                             1.2.5
colorcet                              3.1.0
colorlover                            0.3.0
colour                                0.1.5
community                             1.0.0b1
confection                            0.1.5
cons                                  0.4.7
contourpy                             1.3.3
cramjam                               2.11.0
cryptography                          43.0.3
cuda-python                           12.6.2.post1
cudf-cu12                             25.6.0
cudf-polars-cu12                      25.6.0
cufflinks                             0.17.3
cuml-cu12                             25.6.0
cupy-cuda12x                          13.3.0
curl_cffi                             0.13.0
cuvs-cu12                             25.6.1
cvxopt                                1.3.2
cvxpy                                 1.6.7
cycler                                0.12.1
cyipopt                               1.5.0
cymem                                 2.0.11
Cython                                3.0.12
dask                                  2025.5.0
dask-cuda                             25.6.0
dask-cudf-cu12                        25.6.0
dataproc-spark-connect                0.8.3
datasets                              4.0.0
db-dtypes                             1.4.3
dbus-python                           1.2.18
debugpy                               1.8.15
decorator                             4.4.2
defusedxml                            0.7.1
diffusers                             0.35.1
dill                                  0.3.8
distributed                           2025.5.0
distributed-ucxx-cu12                 0.44.0
distro                                1.9.0
dlib                                  19.24.6
dm-tree                               0.1.9
docstring_parser                      0.17.0
docutils                              0.21.2
dopamine_rl                           4.1.2
duckdb                                1.3.2
earthengine-api                       1.5.24
easydict                              1.13
editdistance                          0.8.1
eerepr                                0.1.2
einops                                0.8.1
en_core_web_sm                        3.8.0
entrypoints                           0.4
et_xmlfile                            2.0.0
etils                                 1.13.0
etuples                               0.3.10
Farama-Notifications                  0.0.4
fastai                                2.8.4
fastapi                               0.116.1
fastcore                              1.8.8
fastdownload                          0.0.7
fastjsonschema                        2.21.2
fastprogress                          1.0.3
fastrlock                             0.8.3
fasttransform                         0.0.2
ffmpy                                 0.6.1
filelock                              3.19.1
firebase-admin                        6.9.0
Flask                                 3.1.2
flatbuffers                           25.2.10
flax                                  0.10.6
folium                                0.20.0
fonttools                             4.59.2
fqdn                                  1.5.1
frozendict                            2.4.6
frozenlist                            1.7.0
fsspec                                2025.3.0
future                                1.0.0
gast                                  0.6.0
gcsfs                                 2025.3.0
GDAL                                  3.8.4
gdown                                 5.2.0
geemap                                0.35.3
geocoder                              1.38.1
geographiclib                         2.1
geopandas                             1.1.1
geopy                                 2.4.1
gin-config                            0.5.0
gitdb                                 4.0.12
GitPython                             3.1.45
glob2                                 0.7
google                                2.0.3
google-adk                            1.13.0
google-ai-generativelanguage          0.6.15
google-api-core                       2.25.1
google-api-python-client              2.181.0
google-auth                           2.38.0
google-auth-httplib2                  0.2.0
google-auth-oauthlib                  1.2.2
google-cloud-aiplatform               1.111.0
google-cloud-appengine-logging        1.6.2
google-cloud-audit-log                0.3.2
google-cloud-bigquery                 3.36.0
google-cloud-bigquery-connection      1.18.3
google-cloud-bigquery-storage         2.33.0
google-cloud-bigtable                 2.32.0
google-cloud-core                     2.4.3
google-cloud-dataproc                 5.21.0
google-cloud-datastore                2.21.0
google-cloud-firestore                2.21.0
google-cloud-functions                1.20.4
google-cloud-language                 2.17.2
google-cloud-logging                  3.12.1
google-cloud-resource-manager         1.14.2
google-cloud-secret-manager           2.24.0
google-cloud-spanner                  3.57.0
google-cloud-speech                   2.33.0
google-cloud-storage                  2.19.0
google-cloud-trace                    1.16.2
google-cloud-translate                3.21.1
google-colab                          1.0.0
google-crc32c                         1.7.1
google-genai                          1.33.0
google-generativeai                   0.8.5
google-pasta                          0.2.0
google-resumable-media                2.7.2
googleapis-common-protos              1.70.0
googledrivedownloader                 1.1.0
gradio                                5.44.1
gradio_client                         1.12.1
graphviz                              0.21
greenlet                              3.2.4
groovy                                0.1.2
grpc-google-iam-v1                    0.14.2
grpc-interceptor                      0.15.4
grpcio                                1.74.0
grpcio-status                         1.71.2
grpclib                               0.4.8
gspread                               6.2.1
gspread-dataframe                     4.0.0
gym                                   0.25.2
gym-notices                           0.1.0
gymnasium                             1.2.0
h11                                   0.16.0
h2                                    4.3.0
h5netcdf                              1.6.4
h5py                                  3.14.0
hdbscan                               0.8.40
hf_transfer                           0.1.9
hf-xet                                1.1.9
highspy                               1.11.0
holidays                              0.80
holoviews                             1.21.0
hpack                                 4.1.0
html5lib                              1.1
httpcore                              1.0.9
httpimport                            1.4.1
httplib2                              0.30.0
httpx                                 0.28.1
httpx-sse                             0.4.1
huggingface-hub                       0.34.4
humanize                              4.13.0
hyperframe                            6.1.0
hyperopt                              0.2.7
ibis-framework                        9.5.0
idna                                  3.10
imageio                               2.37.0
imageio-ffmpeg                        0.6.0
imagesize                             1.4.1
imbalanced-learn                      0.14.0
immutabledict                         4.2.1
importlib_metadata                    8.7.0
importlib_resources                   6.5.2
imutils                               0.5.4
inflect                               7.5.0
iniconfig                             2.1.0
intel-cmplr-lib-ur                    2025.2.1
intel-openmp                          2025.2.1
ipyevents                             2.0.2
ipyfilechooser                        0.6.0
ipykernel                             6.17.1
ipyleaflet                            0.20.0
ipyparallel                           8.8.0
ipython                               7.34.0
ipython-genutils                      0.2.0
ipython-sql                           0.5.0
ipytree                               0.2.2
ipywidgets                            7.7.1
isoduration                           20.11.0
itsdangerous                          2.2.0
jaraco.classes                        3.4.0
jaraco.context                        6.0.1
jaraco.functools                      4.3.0
jax                                   0.5.3
jax-cuda12-pjrt                       0.5.3
jax-cuda12-plugin                     0.5.3
jaxlib                                0.5.3
jeepney                               0.9.0
jieba                                 0.42.1
Jinja2                                3.1.6
jiter                                 0.10.0
joblib                                1.5.2
jsonpatch                             1.33
jsonpickle                            4.1.1
jsonpointer                           3.0.0
jsonschema                            4.25.1
jsonschema-specifications             2025.4.1
jupyter_client                        7.4.9
jupyter-console                       6.6.3
jupyter_core                          5.8.1
jupyter-events                        0.12.0
jupyter_kernel_gateway                2.5.2
jupyter-leaflet                       0.20.0
jupyter_server                        2.14.0
jupyter_server_terminals              0.5.3
jupyterlab_pygments                   0.3.0
jupyterlab_widgets                    3.0.15
jupytext                              1.17.3
kaggle                                1.7.4.5
kagglehub                             0.3.13
keras                                 3.10.0
keras-hub                             0.21.1
keras-nlp                             0.21.1
keyring                               25.6.0
keyrings.google-artifactregistry-auth 1.1.2
kiwisolver                            1.4.9
langchain                             0.3.27
langchain-core                        0.3.75
langchain-text-splitters              0.3.11
langcodes                             3.5.0
langsmith                             0.4.24
language_data                         1.3.0
lark                                  1.2.2
launchpadlib                          1.10.16
lazr.restfulclient                    0.14.4
lazr.uri                              1.0.6
lazy_loader                           0.4
libclang                              18.1.1
libcudf-cu12                          25.6.0
libcugraph-cu12                       25.6.0
libcuml-cu12                          25.6.0
libcuvs-cu12                          25.6.1
libkvikio-cu12                        25.6.0
libpysal                              4.13.0
libraft-cu12                          25.6.0
librmm-cu12                           25.6.0
librosa                               0.11.0
libucx-cu12                           1.18.1
libucxx-cu12                          0.44.0
lightgbm                              4.6.0
linkify-it-py                         2.0.3
llvmlite                              0.43.0
locket                                1.0.0
logical-unification                   0.4.6
lxml                                  5.4.0
Mako                                  1.3.10
marisa-trie                           1.3.1
Markdown                              3.9
markdown-it-py                        4.0.0
MarkupSafe                            3.0.2
matplotlib                            3.10.0
matplotlib-inline                     0.1.7
matplotlib-venn                       1.1.2
mcp                                   1.13.1
mdit-py-plugins                       0.5.0
mdurl                                 0.1.2
miniKanren                            1.0.5
missingno                             0.5.2
mistune                               3.1.4
mizani                                0.13.5
mkl                                   2025.2.0
ml_dtypes                             0.5.3
mlxtend                               0.23.4
more-itertools                        10.8.0
moviepy                               1.0.3
mpmath                                1.3.0
msgpack                               1.1.1
multidict                             6.6.4
multipledispatch                      1.0.0
multiprocess                          0.70.16
multitasking                          0.0.12
murmurhash                            1.0.13
music21                               9.3.0
namex                                 0.1.0
narwhals                              2.3.0
natsort                               8.4.0
nbclassic                             1.3.2
nbclient                              0.10.2
nbconvert                             7.16.6
nbformat                              5.10.4
ndindex                               1.10.0
nest-asyncio                          1.6.0
networkx                              3.5
nibabel                               5.3.2
nltk                                  3.9.1
notebook                              6.5.7
notebook_shim                         0.2.4
numba                                 0.60.0
numba-cuda                            0.11.0
numexpr                               2.11.0
numpy                                 2.0.2
nvidia-cublas-cu12                    12.6.4.1
nvidia-cuda-cupti-cu12                12.6.80
nvidia-cuda-nvcc-cu12                 12.5.82
nvidia-cuda-nvrtc-cu12                12.6.77
nvidia-cuda-runtime-cu12              12.6.77
nvidia-cudnn-cu12                     9.10.2.21
nvidia-cufft-cu12                     11.3.0.4
nvidia-cufile-cu12                    1.11.1.6
nvidia-curand-cu12                    10.3.7.77
nvidia-cusolver-cu12                  11.7.1.2
nvidia-cusparse-cu12                  12.5.4.2
nvidia-cusparselt-cu12                0.7.1
nvidia-ml-py                          12.575.51
nvidia-nccl-cu12                      2.27.3
nvidia-nvjitlink-cu12                 12.6.85
nvidia-nvtx-cu12                      12.6.77
nvtx                                  0.2.13
nx-cugraph-cu12                       25.6.0
oauth2client                          4.1.3
oauthlib                              3.3.1
omegaconf                             2.3.0
openai                                1.106.1
opencv-contrib-python                 4.12.0.88
opencv-python                         4.12.0.88
opencv-python-headless                4.12.0.88
openpyxl                              3.1.5
opentelemetry-api                     1.36.0
opentelemetry-exporter-gcp-trace      1.9.0
opentelemetry-resourcedetector-gcp    1.9.0a0
opentelemetry-sdk                     1.36.0
opentelemetry-semantic-conventions    0.57b0
opt_einsum                            3.4.0
optax                                 0.2.5
optree                                0.17.0
orbax-checkpoint                      0.11.24
orjson                                3.11.3
osqp                                  1.0.4
overrides                             7.7.0
packaging                             25.0
pandas                                2.2.2
pandas-datareader                     0.10.0
pandas-gbq                            0.29.2
pandas-stubs                          2.2.2.240909
pandocfilters                         1.5.1
panel                                 1.7.5
param                                 2.2.1
parso                                 0.8.5
parsy                                 2.1
partd                                 1.4.2
patsy                                 1.0.1
peewee                                3.18.2
peft                                  0.17.1
pexpect                               4.9.0
pickleshare                           0.7.5
pillow                                11.3.0
pip                                   24.1.2
platformdirs                          4.4.0
plotly                                5.24.1
plotnine                              0.14.5
pluggy                                1.6.0
plum-dispatch                         2.5.7
ply                                   3.11
polars                                1.25.2
pooch                                 1.8.2
portpicker                            1.5.2
preshed                               3.0.10
prettytable                           3.16.0
proglog                               0.1.12
progressbar2                          4.5.0
prometheus_client                     0.22.1
promise                               2.3
prompt_toolkit                        3.0.52
propcache                             0.3.2
prophet                               1.1.7
proto-plus                            1.26.1
protobuf                              5.29.5
psutil                                5.9.5
psycopg2                              2.9.10
psygnal                               0.14.1
ptyprocess                            0.7.0
py-cpuinfo                            9.0.0
py4j                                  0.10.9.7
pyarrow                               18.1.0
pyasn1                                0.6.1

In [2]:
# !conda install pandas

import pandas as pd

## Loading Data

### Notes

- We can load data from a CSV using `pd.read_csv()`
- We can also load data from an Excel file using `pd.read_excel()`

In [7]:
# pd.read_excel('path_to_file.xlsx')

df = pd.read_csv('/content/sample_data/california_housing_test.csv')
display(df)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [8]:
df['households']

0        606.0
1        277.0
2        495.0
3         11.0
4        237.0
         ...
2995     607.0
2996    1036.0
2997     220.0
2998      14.0
2999     260.0
Name: households, Length: 3000, dtype: float64

In [9]:
df.total_rooms

0       3885.0
1       1510.0
2       3589.0
3         67.0
4       1241.0
         ...
2995    1450.0
2996    5257.0
2997     956.0
2998      96.0
2999    1765.0
Name: total_rooms, Length: 3000, dtype: float64

In [10]:
df.total_rooms[0]

np.float64(3885.0)

### Example

This lets us run the code in Collab Notebooks without any troubles, but you will have to load and install the `datasets` library every time you open a new session.

NOTE: In Colab or if running locally, you need to install datasets library first.

In [11]:
# !conda install datasets

# OR

!pip install -U datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.19.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.34.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.12.15)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.1.9)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2025.8.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.20.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

To load in the latest dataset use this code.

In [13]:
from datasets import load_dataset

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
dataset

DatasetDict({
    train: Dataset({
        features: ['job_title_short', 'job_title', 'job_location', 'job_via', 'job_schedule_type', 'job_work_from_home', 'search_location', 'job_posted_date', 'job_no_degree_mention', 'job_health_insurance', 'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg', 'company_name', 'job_skills', 'job_type_skills'],
        num_rows: 785741
    })
})

In [18]:
df = dataset['train'].to_pandas()
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

**Note:** For the rest of the sections in this course we'll be doing some exploratory data analysis (EDA) to learn more about the dataset we have. This is a crucial first step so we understand the dataset before doing more advanced analysis and visualization.

## DataFrames Intro

#### What is it?

- A DataFrame is a 2-dimensional labeled data structure with columns of potentially different types.
- It's like a table in a relational database or a spreadsheet.

#### Rows and Columns
- DataFrames consist of rows and columns, where each row represents a single observation or record, and each column represents a variable or feature.

In [ ]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

#### Column Names

- Column names provide labels for each column in the DataFrame
- They allow for easy reference and manipulation of data

In [ ]:
df['job_title_short']

0         Senior Data Engineer
1                 Data Analyst
2                Data Engineer
3                Data Engineer
4                Data Engineer
                  ...
785736       Software Engineer
785737            Data Analyst
785738        Business Analyst
785739           Data Engineer
785740       Software Engineer
Name: job_title_short, Length: 785741, dtype: object

Note: you get info on column name, length, and dtype.

You can also access column with dot notation.

In [ ]:
df.job_title_short

0         Senior Data Engineer
1                 Data Analyst
2                Data Engineer
3                Data Engineer
4                Data Engineer
                  ...
785736       Software Engineer
785737            Data Analyst
785738        Business Analyst
785739           Data Engineer
785740       Software Engineer
Name: job_title_short, Length: 785741, dtype: object

#### Index
- DataFrames have an index, which provides a label for each row. By default, it's a sequence of integers starting from 0, but it can be customized.

In [ ]:
# Access a row by index
df.job_title_short[785740]

'Software Engineer'

#### Data Inspection (upcoming)

Dataframes have a ton of methods to inspect them!

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB